# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: web-api-virtual-service
#   namespace: argocd-workshop
# spec:
#   hosts:
#   - "api.argocd-workshop.com" # External cluster communication
#   - "web-api-service"         # Internal cluster communication ( Istio proxy (sidecar) ) 
#   gateways:
#   - istio-gateway
#   - mesh                      # Require for internal cluster communication
#   http:
#   - match:
#     - uri:
#         prefix: /
#       headers:                # If request sent with canary-version header equal version-1 
#         canary-version:       # curl -H 'canary-version: version-1' http://api.argocd-workshop.com/tasks 
#           exact: version-1
#     fault:                    # Add 5s delay
#       delay:
#         percent: 0
#         fixedDelay: 5s
#     route:
#     - destination:
#         port:
#           number: 3111
#         host: web-api-service
#         subset: v1
#   - route:
#     - destination:
#         port:
#           number: 3111
#         host: web-api-service
#         subset: v2  
