---
# Deployment definition for mysql pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: k8s-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          env:
            - name: MYSQL_DATABASE
              value: main
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-initdb-config
