---
# Service definition for mysql 
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: k8s-workshop
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306