# Deployment definition for wep-api pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  namespace: k8s-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: auth-api
        version: v1
    spec:
      containers:
        - name: auth-api
          image: chenlevin/k8s-workshop-auth-api
          imagePullPolicy: Always
          ports:
            - containerPort: 3111
          env:
            - name: PORT
              value: "3111"
            - name: MYSQL_HOST
              value: mysql-service
            - name: MYSQL_PORT
              value: "3306"
          resources:
            requests:
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 3111
            initialDelaySeconds: 10
            periodSeconds: 5

