FROM node:14.15-alpine as build

WORKDIR /usr/local/web-app

COPY ./web-app/package*.json /usr/local/web-app/

RUN npm ci

COPY ./web-app /usr/local/web-app/

RUN npm run build


FROM node:14.15-alpine

WORKDIR /usr/local/web-hosting

ENV APP_FOLDER dist/

COPY --from=build /usr/local/web-app/dist/web-app/ /usr/local/web-hosting/dist

COPY ./web-hosting /usr/local/web-hosting

RUN npm ci

RUN apk --update --no-cache add curl

CMD ["node", "main.js"]