apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: "*.k8s-workshop.com"
    descriptors:
      - key: API_PATH
        value: "/tasks"
        descriptors:
          - key: remote_address
            rate_limit:
              unit: minute
              requests_per_unit: 100
      - key: API_PATH
        descriptors:
          - key: remote_address
            rate_limit:
              unit: minute
              requests_per_unit: 200
      - key: HOST_PATH
        rate_limit:
          unit: minute
          requests_per_unit: 500