# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: ratelimit-config
# data:
#   config.yaml: |
#     domain: "*.argocd-workshop.com"
#     descriptors:
#       - key: API_PATH
#         value: "/tasks"
#         rate_limit:
#           unit: minute
#           requests_per_unit: 1
#       - key: API_PATH
#         rate_limit:
#           unit: minute
#           requests_per_unit: 10
#       - key: HOST_PATH
#         rate_limit:
#           unit: minute
#           requests_per_unit: 15