apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: "*.k8s-workshop.com"
    descriptors:
      - key: API_PATH
        value: "/tasks"
        rate_limit:
          unit: minute
          requests_per_unit: 2
      - key: API_PATH
        rate_limit:
          unit: minute
          requests_per_unit: 5
      - key: HOST_PATH
        rate_limit:
          unit: minute
          requests_per_unit: 10