# Service definition for web-api
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: k8s-workshop
spec:
  selector:
    app: api-gateway
  ports:
  - port: 3110
    targetPort: 3110
  type: ClusterIP
