apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: web-api-destination-rule
  namespace: k8s-workshop
spec:
  host: tasks-api-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
