apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tasks-api-virtual-service
  namespace: k8s-workshop
spec:
  hosts:
    - "api.k8s-workshop.com"      # External cluster communication
    - "tasks-api-service"         # Internal cluster communication ( Istio proxy (sidecar) ) 
  gateways:
    - istio-gateway
    - mesh                         # Require for internal cluster communication
  http:
      - route:
        - destination:
            port:
              number: 3112
            host: tasks-api-service
            subset: v1
          weight: 50
        - destination:
            port:
              number: 3112
            host: tasks-api-service
            subset: v2
          weight: 50  
